FROM maven:3.9-eclipse-temurin-21
WORKDIR /build
COPY pom.xml .
RUN mvn dependency:go-offline -B
COPY src ./src
RUN mvn package -DskipTests -B
EXPOSE 8080
CMD ["java", "-jar", "target/tekbook-0.0.1-SNAPSHOT.jar"]
